### PR TITLE
Indigo feature

### PR DESCRIPTION
**Pull request by ipa-josh**
features added for sensors with limited opening angle by using odometry in dependence of covariance of matched scan
added new parameters:
 * OdometryCovarianceDistance: Estimated covariance for odometry (translational part)
 * OdometryCovarianceAngular: Estimated covariance for odometry (rotational part)

fixed bugs regarding:
 * inverse of matrix failed
 * parameter passing mixed up

### CODE REVIEW

**Comment by mgruhler** [comment]
the bugfixes are also in a seperate PR #12

**Comment by mgruhler** [comment]
ping @mikeferguson

**Comment by lucbettaieb** [comment]
@ipa-josh any word on this?

**Comment by lucbettaieb** [comment]
@ipa-josh I'm going to close this for now since it seems to be stale.

Please, open a new pull request with fewer commit describing your changes in more detail and I'll review it.

**Pull request closed without merging**
