### PR TITLE
Feature/invalid scans1.1.4

### PR DESCRIPTION
**Pull request by ghost**
I adapted open_karto to work with the infinite readings from the Robopeak lidar driver on an Odroid XU4 (Exynos5422 Cortex™-A15 2Ghz and Cortex™-A7 Octa core CPUs, probably an ARM issue). The problem is that on the Odroid this infinite readings mess up the scan matching.
Without the patch:
ros-slam_orig-karto_odroid
With the patch:
ros-slam_patched-karto_odroid

On a generic pc (Intel Core i5) this doesn't happen:
Without patch:
ros-slam_orig-karto

Is it right that the scan matcher doesn't consider min and max range?
If you need more information ask and I will be happy to provide them.
I can provide also a rosbag file with laserscan data and odometry to reproduce the problem if you want.

### CODE REVIEW

**Comment by ghost** [comment]
Just by the way, the graph is in wrong location because of a misconfigured `frame_id`.

**Comment by mikeferguson** [comment]
@rctoris can you take a look at this

**Comment by rctoris** [comment]
Looks good!

**Comment by mikeferguson** [comment]
@mig-em can you squash these commits into a single one so it is easier for future users/maintainers to see that these changes are related. Thanks!

**Comment by ghost** [comment]
I squashed them.

**Pull request merged**
