### PR TITLE
Changes from PAL Robotics

### PR DESCRIPTION
**Pull request by po1**
Here are a few changes that we have on `open_karto` at PAL.

Most of these commits only change little details, and fix cppcheck-related issues.
The following commits actually change the logic:
- 418cdca adds an accessor to switch the scan matcher on/off at runtime
- 3399878 and 978a31a solve problems, but I fail to remember what exactly. @RainCT do you remember?

Since whitespaces & newlines have been touched, the global diff will sadly not be of great help, so individual commits should be inspected instead.

### CODE REVIEW

**Comment by mikeferguson** [comment]
I might not get a chance to look at this in detail until after ROSCon.. but I will definitely get to it next week at the latest.

**Comment by jonbinney** [comment]
@liz-murphy has been using open_karto quite a bit lately - liz do you want to look this over as well?

**Comment by RainCT** [comment]
Those two patches are for thread safety (OpenKarto wasn't really designed
for this, but I could achieve some parallelism).
El dia 09/09/2014 11.57, "Paul Mathieu" notifications@github.com va
escriure:

**Comment by mikeferguson** [comment]
Built and tested against several of my bag files, LGTM.

**Pull request merged**
