### PR TITLE
Indigo bugfixes

### PR DESCRIPTION
**Pull request by ipa-josh**
fixed bugs regarding:
 * inverse of matrix failed
 * parameter passing mixed up

### CODE REVIEW

**Comment by mgruhler** [comment]
ping @mikeferguson

**Comment by mikeferguson** [comment]
@ipa-josh -- I finally got a chance to try this out -- but I'm not having much success (hitting assertions due to parameter switch). Can you tell me how you tested? What platform/parameters?

**Comment by lucbettaieb** [comment]
@ipa-josh ^

**Comment by lucbettaieb** [comment]
@ipa-josh ping ping

**Comment by chriser-** [comment]
In case anyone is still working on this, the parameter is still wrong. The switch was correct, but you also have to change
`m_pMapper->m_pFineSearchAngleOffset->GetValue()` to `m_pMapper->m_pCoarseSearchAngleOffset->GetValue()` in the line above.

**Comment by lucbettaieb** [comment]
Super stale, closing.

**Pull request closed without merging**
